sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t lunaticpraveen/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true lunaticpraveen/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "docker-react"
  env: "Docker-react-env"
  bucket_name: "elasticbeanstalk-ap-south-1-507146831009"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY  
